spring:
  application:
    name: userCenter
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234567890
    url: jdbc:mysql://localhost:3306/joe
server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
